<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Authmenu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Authmenu_model');
    } 

    /*
     * Listing of authmenu
     */
    function index()
    {
        $data['authmenu'] = $this->Authmenu_model->get_all_authmenu();
        
        $data['_view'] = 'authmenu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new authmenu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'authid' => $this->input->post('authid'),
				'authmenu' => $this->input->post('authmenu'),
            );
            
            $authmenu_id = $this->Authmenu_model->add_authmenu($params);
            redirect('authmenu/index');
        }
        else
        {            
            $data['_view'] = 'authmenu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a authmenu
     */
    function edit($)
    {   
        // check if the authmenu exists before trying to edit it
        $data['authmenu'] = $this->Authmenu_model->get_authmenu($);
        
        if(isset($data['authmenu']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'authid' => $this->input->post('authid'),
					'authmenu' => $this->input->post('authmenu'),
                );

                $this->Authmenu_model->update_authmenu($,$params);            
                redirect('authmenu/index');
            }
            else
            {
                $data['_view'] = 'authmenu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The authmenu you are trying to edit does not exist.');
    } 

    /*
     * Deleting authmenu
     */
    function remove($)
    {
        $authmenu = $this->Authmenu_model->get_authmenu($);

        // check if the authmenu exists before trying to delete it
        if(isset($authmenu['']))
        {
            $this->Authmenu_model->delete_authmenu($);
            redirect('authmenu/index');
        }
        else
            show_error('The authmenu you are trying to delete does not exist.');
    }
    
}
