<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Companytype extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Companytype_model');
    } 

    /*
     * Listing of companytype
     */
    function index()
    {
        $data['companytype'] = $this->Companytype_model->get_all_companytype();
        
        $data['_view'] = 'companytype/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new companytype
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'description' => $this->input->post('description'),
				'MenuId' => $this->input->post('MenuId'),
				'busrole' => $this->input->post('busrole'),
            );
            
            $companytype_id = $this->Companytype_model->add_companytype($params);
            redirect('companytype/index');
        }
        else
        {            
            $data['_view'] = 'companytype/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a companytype
     */
    function edit($typeId)
    {   
        // check if the companytype exists before trying to edit it
        $data['companytype'] = $this->Companytype_model->get_companytype($typeId);
        
        if(isset($data['companytype']['typeId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'description' => $this->input->post('description'),
					'MenuId' => $this->input->post('MenuId'),
					'busrole' => $this->input->post('busrole'),
                );

                $this->Companytype_model->update_companytype($typeId,$params);            
                redirect('companytype/index');
            }
            else
            {
                $data['_view'] = 'companytype/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The companytype you are trying to edit does not exist.');
    } 

    /*
     * Deleting companytype
     */
    function remove($typeId)
    {
        $companytype = $this->Companytype_model->get_companytype($typeId);

        // check if the companytype exists before trying to delete it
        if(isset($companytype['typeId']))
        {
            $this->Companytype_model->delete_companytype($typeId);
            redirect('companytype/index');
        }
        else
            show_error('The companytype you are trying to delete does not exist.');
    }
    
}
