<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Company_model');
    } 

    /*
     * Listing of company
     */
    function index()
    {
        $data['company'] = $this->Company_model->get_all_company();
        
        $data['_view'] = 'company/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new company
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'code' => $this->input->post('code'),
				'typeId' => $this->input->post('typeId'),
				'lobId' => $this->input->post('lobId'),
				'name' => $this->input->post('name'),
				'description' => $this->input->post('description'),
				'menuId' => $this->input->post('menuId'),
            );
            
            $company_id = $this->Company_model->add_company($params);
            redirect('company/index');
        }
        else
        {            
            $data['_view'] = 'company/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a company
     */
    function edit($companyId)
    {   
        // check if the company exists before trying to edit it
        $data['company'] = $this->Company_model->get_company($companyId);
        
        if(isset($data['company']['companyId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'code' => $this->input->post('code'),
					'typeId' => $this->input->post('typeId'),
					'lobId' => $this->input->post('lobId'),
					'name' => $this->input->post('name'),
					'description' => $this->input->post('description'),
					'menuId' => $this->input->post('menuId'),
                );

                $this->Company_model->update_company($companyId,$params);            
                redirect('company/index');
            }
            else
            {
                $data['_view'] = 'company/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The company you are trying to edit does not exist.');
    } 

    /*
     * Deleting company
     */
    function remove($companyId)
    {
        $company = $this->Company_model->get_company($companyId);

        // check if the company exists before trying to delete it
        if(isset($company['companyId']))
        {
            $this->Company_model->delete_company($companyId);
            redirect('company/index');
        }
        else
            show_error('The company you are trying to delete does not exist.');
    }
    
}
