<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Employee_model');
    } 

    /*
     * Listing of employees
     */
    function index()
    {
        $data['employees'] = $this->Employee_model->get_all_employees();
        
        $data['_view'] = 'employee/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new employee
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'lastName' => $this->input->post('lastName'),
				'firstName' => $this->input->post('firstName'),
				'extension' => $this->input->post('extension'),
				'email' => $this->input->post('email'),
				'officeCode' => $this->input->post('officeCode'),
				'file_url' => $this->input->post('file_url'),
				'jobTitle' => $this->input->post('jobTitle'),
            );
            
            $employee_id = $this->Employee_model->add_employee($params);
            redirect('employee/index');
        }
        else
        {            
            $data['_view'] = 'employee/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a employee
     */
    function edit($employeeNumber)
    {   
        // check if the employee exists before trying to edit it
        $data['employee'] = $this->Employee_model->get_employee($employeeNumber);
        
        if(isset($data['employee']['employeeNumber']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'lastName' => $this->input->post('lastName'),
					'firstName' => $this->input->post('firstName'),
					'extension' => $this->input->post('extension'),
					'email' => $this->input->post('email'),
					'officeCode' => $this->input->post('officeCode'),
					'file_url' => $this->input->post('file_url'),
					'jobTitle' => $this->input->post('jobTitle'),
                );

                $this->Employee_model->update_employee($employeeNumber,$params);            
                redirect('employee/index');
            }
            else
            {
                $data['_view'] = 'employee/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The employee you are trying to edit does not exist.');
    } 

    /*
     * Deleting employee
     */
    function remove($employeeNumber)
    {
        $employee = $this->Employee_model->get_employee($employeeNumber);

        // check if the employee exists before trying to delete it
        if(isset($employee['employeeNumber']))
        {
            $this->Employee_model->delete_employee($employeeNumber);
            redirect('employee/index');
        }
        else
            show_error('The employee you are trying to delete does not exist.');
    }
    
}
