<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Home extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Auth_model');
    } 
	
    function index()
    {
        $this->load->view('home/index');
    }

}