<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lob extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Lob_model');
    } 

    /*
     * Listing of lob
     */
    function index()
    {
        $data['lob'] = $this->Lob_model->get_all_lob();
        
        $data['_view'] = 'lob/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new lob
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'desc' => $this->input->post('desc'),
            );
            
            $lob_id = $this->Lob_model->add_lob($params);
            redirect('lob/index');
        }
        else
        {            
            $data['_view'] = 'lob/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a lob
     */
    function edit($lobId)
    {   
        // check if the lob exists before trying to edit it
        $data['lob'] = $this->Lob_model->get_lob($lobId);
        
        if(isset($data['lob']['lobId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'desc' => $this->input->post('desc'),
                );

                $this->Lob_model->update_lob($lobId,$params);            
                redirect('lob/index');
            }
            else
            {
                $data['_view'] = 'lob/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The lob you are trying to edit does not exist.');
    } 

    /*
     * Deleting lob
     */
    function remove($lobId)
    {
        $lob = $this->Lob_model->get_lob($lobId);

        // check if the lob exists before trying to delete it
        if(isset($lob['lobId']))
        {
            $this->Lob_model->delete_lob($lobId);
            redirect('lob/index');
        }
        else
            show_error('The lob you are trying to delete does not exist.');
    }
    
}
