<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_model');
    } 

    /*
     * Listing of product
     */
    function index()
    {
        $data['product'] = $this->Product_model->get_all_product();
        
        $data['_view'] = 'product/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new product
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'addressId' => $this->input->post('addressId'),
				'prodTypeId' => $this->input->post('prodTypeId'),
				'name' => $this->input->post('name'),
				'picturePath' => $this->input->post('picturePath'),
				'Description' => $this->input->post('Description'),
            );
            
            $product_id = $this->Product_model->add_product($params);
            redirect('product/index');
        }
        else
        {            
            $data['_view'] = 'product/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a product
     */
    function edit($productId)
    {   
        // check if the product exists before trying to edit it
        $data['product'] = $this->Product_model->get_product($productId);
        
        if(isset($data['product']['productId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'addressId' => $this->input->post('addressId'),
					'prodTypeId' => $this->input->post('prodTypeId'),
					'name' => $this->input->post('name'),
					'picturePath' => $this->input->post('picturePath'),
					'Description' => $this->input->post('Description'),
                );

                $this->Product_model->update_product($productId,$params);            
                redirect('product/index');
            }
            else
            {
                $data['_view'] = 'product/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The product you are trying to edit does not exist.');
    } 

    /*
     * Deleting product
     */
    function remove($productId)
    {
        $product = $this->Product_model->get_product($productId);

        // check if the product exists before trying to delete it
        if(isset($product['productId']))
        {
            $this->Product_model->delete_product($productId);
            redirect('product/index');
        }
        else
            show_error('The product you are trying to delete does not exist.');
    }
    
}
