<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Producttype extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Producttype_model');
    } 

    /*
     * Listing of producttype
     */
    function index()
    {
        $data['producttype'] = $this->Producttype_model->get_all_producttype();
        
        $data['_view'] = 'producttype/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new producttype
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'description' => $this->input->post('description'),
				'menuId' => $this->input->post('menuId'),
            );
            
            $producttype_id = $this->Producttype_model->add_producttype($params);
            redirect('producttype/index');
        }
        else
        {            
            $data['_view'] = 'producttype/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a producttype
     */
    function edit($prodTypeId)
    {   
        // check if the producttype exists before trying to edit it
        $data['producttype'] = $this->Producttype_model->get_producttype($prodTypeId);
        
        if(isset($data['producttype']['prodTypeId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'description' => $this->input->post('description'),
					'menuId' => $this->input->post('menuId'),
                );

                $this->Producttype_model->update_producttype($prodTypeId,$params);            
                redirect('producttype/index');
            }
            else
            {
                $data['_view'] = 'producttype/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The producttype you are trying to edit does not exist.');
    } 

    /*
     * Deleting producttype
     */
    function remove($prodTypeId)
    {
        $producttype = $this->Producttype_model->get_producttype($prodTypeId);

        // check if the producttype exists before trying to delete it
        if(isset($producttype['prodTypeId']))
        {
            $this->Producttype_model->delete_producttype($prodTypeId);
            redirect('producttype/index');
        }
        else
            show_error('The producttype you are trying to delete does not exist.');
    }
    
}
