<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Authmenu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get authmenu by 
     */
    function get_authmenu($)
    {
        return $this->db->get_where('authmenu',array(''=>$))->row_array();
    }
        
    /*
     * Get all authmenu
     */
    function get_all_authmenu()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('authmenu')->result_array();
    }
        
    /*
     * function to add new authmenu
     */
    function add_authmenu($params)
    {
        $this->db->insert('authmenu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update authmenu
     */
    function update_authmenu($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('authmenu',$params);
    }
    
    /*
     * function to delete authmenu
     */
    function delete_authmenu($)
    {
        return $this->db->delete('authmenu',array(''=>$));
    }
}
