<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Auth_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get auth by authId
     */
    function get_auth($authId)
    {
        return $this->db->get_where('auth',array('authId'=>$authId))->row_array();
    }
        
    /*
     * Get all auth
     */
    function get_all_auth()
    {
        $this->db->order_by('authId', 'desc');
        return $this->db->get('auth')->result_array();
    }
        
    /*
     * function to add new auth
     */
    function add_auth($params)
    {
        $this->db->insert('auth',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update auth
     */
    function update_auth($authId,$params)
    {
        $this->db->where('authId',$authId);
        return $this->db->update('auth',$params);
    }
    
    /*
     * function to delete auth
     */
    function delete_auth($authId)
    {
        return $this->db->delete('auth',array('authId'=>$authId));
    }
}
