<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get company by companyId
     */
    function get_company($companyId)
    {
        return $this->db->get_where('company',array('companyId'=>$companyId))->row_array();
    }
        
    /*
     * Get all company
     */
    function get_all_company()
    {
        $this->db->order_by('companyId', 'desc');
        return $this->db->get('company')->result_array();
    }
        
    /*
     * function to add new company
     */
    function add_company($params)
    {
        $this->db->insert('company',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update company
     */
    function update_company($companyId,$params)
    {
        $this->db->where('companyId',$companyId);
        return $this->db->update('company',$params);
    }
    
    /*
     * function to delete company
     */
    function delete_company($companyId)
    {
        return $this->db->delete('company',array('companyId'=>$companyId));
    }
}
