<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Companytype_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get companytype by typeId
     */
    function get_companytype($typeId)
    {
        return $this->db->get_where('companytype',array('typeId'=>$typeId))->row_array();
    }
        
    /*
     * Get all companytype
     */
    function get_all_companytype()
    {
        $this->db->order_by('typeId', 'desc');
        return $this->db->get('companytype')->result_array();
    }
        
    /*
     * function to add new companytype
     */
    function add_companytype($params)
    {
        $this->db->insert('companytype',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update companytype
     */
    function update_companytype($typeId,$params)
    {
        $this->db->where('typeId',$typeId);
        return $this->db->update('companytype',$params);
    }
    
    /*
     * function to delete companytype
     */
    function delete_companytype($typeId)
    {
        return $this->db->delete('companytype',array('typeId'=>$typeId));
    }
}
