<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get employee by employeeNumber
     */
    function get_employee($employeeNumber)
    {
        return $this->db->get_where('employees',array('employeeNumber'=>$employeeNumber))->row_array();
    }
        
    /*
     * Get all employees
     */
    function get_all_employees()
    {
        $this->db->order_by('employeeNumber', 'desc');
        return $this->db->get('employees')->result_array();
    }
        
    /*
     * function to add new employee
     */
    function add_employee($params)
    {
        $this->db->insert('employees',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update employee
     */
    function update_employee($employeeNumber,$params)
    {
        $this->db->where('employeeNumber',$employeeNumber);
        return $this->db->update('employees',$params);
    }
    
    /*
     * function to delete employee
     */
    function delete_employee($employeeNumber)
    {
        return $this->db->delete('employees',array('employeeNumber'=>$employeeNumber));
    }
}
