<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lob_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lob by lobId
     */
    function get_lob($lobId)
    {
        return $this->db->get_where('lob',array('lobId'=>$lobId))->row_array();
    }
        
    /*
     * Get all lob
     */
    function get_all_lob()
    {
        $this->db->order_by('lobId', 'desc');
        return $this->db->get('lob')->result_array();
    }
        
    /*
     * function to add new lob
     */
    function add_lob($params)
    {
        $this->db->insert('lob',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lob
     */
    function update_lob($lobId,$params)
    {
        $this->db->where('lobId',$lobId);
        return $this->db->update('lob',$params);
    }
    
    /*
     * function to delete lob
     */
    function delete_lob($lobId)
    {
        return $this->db->delete('lob',array('lobId'=>$lobId));
    }
}
