<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Producttype_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get producttype by prodTypeId
     */
    function get_producttype($prodTypeId)
    {
        return $this->db->get_where('producttype',array('prodTypeId'=>$prodTypeId))->row_array();
    }
        
    /*
     * Get all producttype
     */
    function get_all_producttype()
    {
        $this->db->order_by('prodTypeId', 'desc');
        return $this->db->get('producttype')->result_array();
    }
        
    /*
     * function to add new producttype
     */
    function add_producttype($params)
    {
        $this->db->insert('producttype',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update producttype
     */
    function update_producttype($prodTypeId,$params)
    {
        $this->db->where('prodTypeId',$prodTypeId);
        return $this->db->update('producttype',$params);
    }
    
    /*
     * function to delete producttype
     */
    function delete_producttype($prodTypeId)
    {
        return $this->db->delete('producttype',array('prodTypeId'=>$prodTypeId));
    }
}
