<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get product by productId
     */
    function get_product($productId)
    {
        return $this->db->get_where('product',array('productId'=>$productId))->row_array();
    }
        
    /*
     * Get all product
     */
    function get_all_product()
    {
        $this->db->order_by('productId', 'desc');
        return $this->db->get('product')->result_array();
    }
        
    /*
     * function to add new product
     */
    function add_product($params)
    {
        $this->db->insert('product',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product
     */
    function update_product($productId,$params)
    {
        $this->db->where('productId',$productId);
        return $this->db->update('product',$params);
    }
    
    /*
     * function to delete product
     */
    function delete_product($productId)
    {
        return $this->db->delete('product',array('productId'=>$productId));
    }
}
